const {app,BrowserWindow,Tray,Menu,screen,ipcMain,nativeImage,clipboard,globalShortcut}=require('electron');
const path=require('path'),fs=require('fs');
let win,tray,isQuitting=false,randomTimer=null,hideTimer=null,hovered=false;
const POPUP_W=320,POPUP_H=118,AUTO_HIDE_MS=12000;
function log(m){try{const d=app.getPath('userData');fs.mkdirSync(d,{recursive:true});fs.appendFileSync(path.join(d,'daily-spark.log'),`[${new Date().toISOString()}] ${m}\n`)}catch{}}
function prefsPath(){return path.join(app.getPath('userData'),'preferences.json')}
function inboxPath(){return path.join(app.getPath('userData'),'spark-inbox.json')}
function getPrefs(){try{return JSON.parse(fs.readFileSync(prefsPath(),'utf8'))}catch{return {randomPopups:true,minHours:2,maxHours:4}}}
function savePrefs(p){fs.writeFileSync(prefsPath(),JSON.stringify({...getPrefs(),...p},null,2));return getPrefs()}
function getInbox(){try{const x=JSON.parse(fs.readFileSync(inboxPath(),'utf8'));return Array.isArray(x)?x:[]}catch{return []}}
function saveInbox(items){fs.writeFileSync(inboxPath(),JSON.stringify(items,null,2));return items}
function classify(text=''){const s=text.toLowerCase();if(/\b(remind|remember|don't forget|do not forget|pending|need to|have to|tomorrow|later|follow.?up)\b/.test(s))return 'Reminder';if(/\b(routine|schedule|habit|every day|daily|morning|evening)\b/.test(s))return 'Routine';if(/\b(food|meal|eat|breakfast|lunch|dinner|protein|snack)\b/.test(s))return 'Food idea';if(/\b(idea|what if|consider|could|experiment|try)\b/.test(s))return 'Idea';if(/\b(motivat|progress|discipline|consisten|keep going|goal)\b/.test(s))return 'Motivation';if(/\b(suggest|recommend|better to|should)\b/.test(s))return 'Suggestion';return 'Talk'}
function addClipboardSpark(){const text=clipboard.readText().replace(/\s+/g,' ').trim();if(!text){showSpark({kind:'Clipboard',text:'Copy a useful thought first, then press Ctrl+Shift+S.',context:'Nothing was saved'});return}const clipped=text.length>360?text.slice(0,357)+'…':text;const items=getInbox();const item={id:Date.now().toString(36),kind:classify(clipped),text:clipped,context:'Conversation takeaway',createdAt:new Date().toISOString()};items.unshift(item);saveInbox(items.slice(0,250));showSpark({...item,kind:'Saved · '+item.kind,context:'Saved locally · it can return later'});log('Clipboard Spark saved')}
function targetBounds(){const d=screen.getDisplayNearestPoint(screen.getCursorScreenPoint()),a=d.workArea;log(`Display scale=${d.scaleFactor} workArea=${JSON.stringify(a)} target=${POPUP_W}x${POPUP_H}`);return {x:Math.round(a.x+a.width-POPUP_W-12),y:Math.round(a.y+a.height-POPUP_H-12),width:POPUP_W,height:POPUP_H}}
function forceBounds(){if(!win||win.isDestroyed())return;const b=targetBounds();win.setBounds(b,false);win.setContentSize(POPUP_W,POPUP_H,false);log(`Actual bounds=${JSON.stringify(win.getBounds())} content=${JSON.stringify(win.getContentBounds())}`)}
function createWindow(){win=new BrowserWindow({width:POPUP_W,height:POPUP_H,show:false,frame:false,transparent:false,backgroundColor:'#fffdf9',resizable:false,movable:false,maximizable:false,minimizable:false,fullscreenable:false,alwaysOnTop:true,skipTaskbar:true,focusable:false,hasShadow:true,autoHideMenuBar:true,webPreferences:{contextIsolation:true,nodeIntegration:false,preload:path.join(__dirname,'preload.js')}});win.setMinimumSize(POPUP_W,POPUP_H);win.setMaximumSize(POPUP_W,POPUP_H);win.setAlwaysOnTop(true,'floating');win.loadFile(path.join(__dirname,'app','index.html'));win.webContents.on('did-finish-load',()=>{win.webContents.setZoomFactor(1);forceBounds()});win.on('resize',forceBounds);win.on('close',e=>{if(!isQuitting){e.preventDefault();win.hide()}})}
function startHide(){clearTimeout(hideTimer);hideTimer=setTimeout(()=>{if(!hovered&&win&&!win.isDestroyed())win.hide();else startHide()},AUTO_HIDE_MS)}
function showSpark(item=null){if(!win||win.isDestroyed())return;forceBounds();if(item)win.webContents.send('display-spark',item);else win.webContents.send('refresh-spark');win.showInactive();startHide();log('Spark shown')}
function scheduleRandom(){clearTimeout(randomTimer);const p=getPrefs();if(!p.randomPopups)return;const min=Math.max(.25,Number(p.minHours)||2)*3600000,max=Math.max(min,Number(p.maxHours)||4)*3600000,delay=Math.floor(min+Math.random()*(max-min));randomTimer=setTimeout(()=>{showSpark();scheduleRandom()},delay)}
function createTray(){const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" rx="8" fill="#24231f"/><path d="M16 5l2.2 7.8L26 15l-7.8 2.2L16 25l-2.2-7.8L6 15l7.8-2.2z" fill="#f3c67a"/></svg>`;const icon=nativeImage.createFromDataURL('data:image/svg+xml;base64,'+Buffer.from(svg).toString('base64')).resize({width:16,height:16});tray=new Tray(icon);tray.setToolTip('Daily Spark');tray.setContextMenu(Menu.buildFromTemplate([{label:'✦ Show Daily Spark',click:()=>showSpark()},{label:'＋ Save clipboard as Spark',click:addClipboardSpark},{label:'Ctrl+Shift+S · quick capture',enabled:false},{type:'separator'},{label:'Quiet Sparks · every 2–4 hours',enabled:false},{label:'Start with Windows',type:'checkbox',checked:app.getLoginItemSettings().openAtLogin,click:i=>app.setLoginItemSettings({openAtLogin:i.checked,path:app.getPath('exe')})},{type:'separator'},{label:'Quit Daily Spark',click:()=>{isQuitting=true;app.quit()}}]));tray.on('click',()=>showSpark())}
const lock=app.requestSingleInstanceLock();if(!lock)app.quit();else{app.on('second-instance',()=>showSpark());app.whenReady().then(()=>{createWindow();createTray();const ok=globalShortcut.register('CommandOrControl+Shift+S',addClipboardSpark);if(!ok)log('Ctrl+Shift+S shortcut unavailable');if(app.isPackaged)app.setLoginItemSettings({openAtLogin:true,path:app.getPath('exe')});setTimeout(()=>showSpark(),1800);scheduleRandom();log('Daily Spark v1.5.1 sizing diagnostic started')})}
ipcMain.on('close-popup',()=>win&&win.hide());ipcMain.on('popup-hover',(_e,on)=>{hovered=on;if(!on)startHide()});ipcMain.on('show-another',()=>win&&win.webContents.send('refresh-spark'));ipcMain.handle('get-inbox',()=>getInbox());ipcMain.handle('get-prefs',getPrefs);ipcMain.handle('save-prefs',(_e,p)=>{const r=savePrefs(p);scheduleRandom();return r});app.on('before-quit',()=>{isQuitting=true;globalShortcut.unregisterAll()});