const {app,BrowserWindow,Tray,Menu,screen,shell,ipcMain,nativeImage}=require('electron');
const path=require('path'),fs=require('fs');
let win,tray,isQuitting=false,randomTimer=null,hideTimer=null,hovered=false;
const AUTO_HIDE_MS=30000;
function log(m){try{const d=app.getPath('userData');fs.mkdirSync(d,{recursive:true});fs.appendFileSync(path.join(d,'daily-spark.log'),`[${new Date().toISOString()}] ${m}\n`)}catch{}}
function prefsPath(){return path.join(app.getPath('userData'),'preferences.json')}
function getPrefs(){try{return JSON.parse(fs.readFileSync(prefsPath(),'utf8'))}catch{return {topics:['AI Trends','Motivation','MMA','Physical Fitness','Art & Music','Upcoming Tasks'],randomPopups:true,minHours:2,maxHours:4}}}
function savePrefs(p){fs.writeFileSync(prefsPath(),JSON.stringify({...getPrefs(),...p},null,2));return getPrefs()}
function createWindow(){win=new BrowserWindow({width:390,height:235,show:false,frame:false,resizable:false,maximizable:false,minimizable:false,alwaysOnTop:true,skipTaskbar:true,backgroundColor:'#f8f4eb',webPreferences:{contextIsolation:true,nodeIntegration:false,preload:path.join(__dirname,'preload.js')}});win.loadFile(path.join(__dirname,'app','index.html'));win.on('close',e=>{if(!isQuitting){e.preventDefault();win.hide()}});win.webContents.on('did-fail-load',(_e,c,d)=>log(`load fail ${c} ${d}`));}
function position(){const display=screen.getDisplayNearestPoint(screen.getCursorScreenPoint()),a=display.workArea,[w,h]=win.getSize();win.setPosition(a.x+a.width-w-14,a.y+a.height-h-14,false)}
function startHide(){clearTimeout(hideTimer);hideTimer=setTimeout(()=>{if(!hovered&&win&&!win.isDestroyed())win.hide();else startHide()},AUTO_HIDE_MS)}
function showSpark(){if(!win||win.isDestroyed())return;position();win.webContents.send('refresh-spark');win.showInactive();win.moveTop();startHide();log('Spark shown')}
function scheduleRandom(){clearTimeout(randomTimer);const p=getPrefs();if(!p.randomPopups)return;const min=Math.max(.25,Number(p.minHours)||2)*3600000,max=Math.max(min,Number(p.maxHours)||4)*3600000,delay=Math.floor(min+Math.random()*(max-min));log(`Next spark in ${Math.round(delay/60000)} min`);randomTimer=setTimeout(()=>{showSpark();scheduleRandom()},delay)}
function createTray(){let icon=nativeImage.createFromPath(path.join(__dirname,'assets','tray.png')).resize({width:16,height:16});tray=new Tray(icon);tray.setToolTip('Daily Spark');tray.setContextMenu(Menu.buildFromTemplate([{label:'✦ Show a Spark now',click:showSpark},{label:'Open Daily Spark',click:showSpark},{type:'separator'},{label:'Random popups: 2–4 hours',enabled:false},{label:'Start with Windows',type:'checkbox',checked:true,click:i=>app.setLoginItemSettings({openAtLogin:i.checked,path:app.getPath('exe')})},{type:'separator'},{label:'Quit Daily Spark',click:()=>{isQuitting=true;app.quit()}}]));tray.on('click',showSpark)}
async function fetchQuotation(){const urls=['https://www.quotationspage.com/random.php3','https://www.quotationspage.com/qotd.html'];for(const url of urls){try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 DailySpark/1.2'}});if(!r.ok)continue;const h=await r.text();let matches=[...h.matchAll(/<dt[^>]*class=["']quote["'][^>]*>([\s\S]*?)<\/dt>[\s\S]*?<dd[^>]*class=["']author["'][^>]*>([\s\S]*?)<\/dd>/gi)];if(!matches.length)matches=[...h.matchAll(/<a[^>]*class=["']quotelink["'][^>]*>([\s\S]*?)<\/a>[\s\S]{0,800}?<a[^>]*href=["'][^"']*quotes\/[^"']+["'][^>]*>([\s\S]*?)<\/a>/gi)];if(matches.length){const m=matches[Math.floor(Math.random()*matches.length)],clean=s=>s.replace(/<[^>]+>/g,' ').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();return {text:clean(m[1]).replace(/^“|”$/g,''),author:clean(m[2]),source:'The Quotations Page',url}}}catch(e){log('quote fetch '+e.message)}}return null}
const lock=app.requestSingleInstanceLock();if(!lock)app.quit();else{app.on('second-instance',showSpark);app.whenReady().then(()=>{createWindow();createTray();app.setLoginItemSettings({openAtLogin:true,path:app.getPath('exe')});setTimeout(showSpark,2500);scheduleRandom();log('Daily Spark v1.2 started')});}
ipcMain.on('close-popup',()=>win&&win.hide());ipcMain.on('open-url',(_e,u)=>{if(/^https?:\/\//i.test(u))shell.openExternal(u)});ipcMain.on('popup-hover',(_e,on)=>{hovered=on;if(!on)startHide()});ipcMain.on('show-another',()=>win&&win.webContents.send('refresh-spark'));ipcMain.handle('get-internet-quote',fetchQuotation);ipcMain.handle('get-prefs',getPrefs);ipcMain.handle('save-prefs',(_e,p)=>{const r=savePrefs(p);scheduleRandom();return r});app.on('before-quit',()=>{isQuitting=true});