const {app,BrowserWindow,Tray,Menu,screen,ipcMain,nativeImage,clipboard,globalShortcut,dialog}=require('electron');
const fs=require('fs'),path=require('path'),AdmZip=require('adm-zip');
app.setName('Daily Spark 2');
let win,tray,current=null,hideTimer=null,randomTimer=null,hovered=false,isQuitting=false;
const W=370,H=165,AUTO_HIDE=15000;
const seed=[
 {kind:'Idea',text:'Turn one useful conversation into one small experiment you can try today.',context:'Daily Spark · starter'},
 {kind:'Suggestion',text:'Pick the smallest useful next step instead of expanding the plan.',context:'Daily Spark · starter'},
 {kind:'Task',text:'Choose one unfinished item and move it to done before starting another.',context:'Daily Spark · starter'},
 {kind:'Reminder',text:'Revisit the conversation that ended with a next step you have not acted on yet.',context:'Daily Spark · starter'},
 {kind:'Joke',text:'My productivity plan was perfect. Then a notification asked if I wanted to be productive.',context:'Daily Spark · quick laugh'},
 {kind:'Break',text:'Two-minute reset: stand up, look away from the screen and move a little.',context:'Daily Spark · break'}
];
function storePath(){return path.join(app.getPath('userData'),'spark-library.json')}
function readStore(){try{const x=JSON.parse(fs.readFileSync(storePath(),'utf8'));return Array.isArray(x)?x:[]}catch{return []}}
function writeStore(x){fs.mkdirSync(app.getPath('userData'),{recursive:true});fs.writeFileSync(storePath(),JSON.stringify(x.slice(0,1000),null,2))}
function clean(s=''){return String(s).replace(/\s+/g,' ').trim()}
function classify(s=''){const t=s.toLowerCase();if(/\b(joke|funny|laugh|humou?r)\b/.test(t))return'Joke';if(/\b(break|rest|stretch|walk|pause)\b/.test(t))return'Break';if(/\b(remind|remember|don't forget|deadline|due|tomorrow|later|follow.?up)\b/.test(t))return'Reminder';if(/\b(todo|task|need to|have to|must|finish|complete|submit|send|call|email|deploy|implement|next step|pending)\b/.test(t))return'Task';if(/\b(suggest|recommend|should|better to|try|consider)\b/.test(t))return'Suggestion';return'Idea'}
function add(text,context='Conversation takeaway'){text=clean(text);if(text.length<18)return null;text=text.slice(0,420);const all=readStore();if(all.some(x=>x.text===text))return null;const item={id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),kind:classify(text),text,context,createdAt:new Date().toISOString(),done:false,snoozedUntil:0};all.unshift(item);writeStore(all);return item}
function contentText(c){if(!c)return'';if(Array.isArray(c.parts))return c.parts.filter(x=>typeof x==='string').join(' ');if(typeof c.text==='string')return c.text;return''}
function importConversations(data){const convs=Array.isArray(data)?data:(data&&Array.isArray(data.conversations)?data.conversations:[]);let added=0;for(const conv of convs){const nodes=Object.values(conv.mapping||{}).filter(n=>n&&n.message).sort((a,b)=>(a.message.create_time||0)-(b.message.create_time||0));for(const n of nodes){const m=n.message,role=m.author&&m.author.role;if(role!=='user'&&role!=='assistant')continue;const text=clean(contentText(m.content));if(text.length<30||text.length>900)continue;if(add(text,`ChatGPT import · ${clean(conv.title||'conversation').slice(0,70)}`))added++}}return added}
async function importHistory(){const r=await dialog.showOpenDialog({title:'Import ChatGPT history',properties:['openFile'],filters:[{name:'ChatGPT export',extensions:['zip','json']}]});if(r.canceled||!r.filePaths[0])return null;try{const p=r.filePaths[0];let data;if(p.toLowerCase().endsWith('.zip')){const z=new AdmZip(p),entry=z.getEntries().find(e=>/(^|\/)conversations\.json$/i.test(e.entryName));if(!entry)throw Error('conversations.json was not found in this export.');data=JSON.parse(entry.getData().toString('utf8'))}else data=JSON.parse(fs.readFileSync(p,'utf8'));const n=importConversations(data);return show({kind:'Idea',text:`Imported ${n} useful conversation takeaways. Daily Spark will resurface them locally.`,context:'Import complete · no API key used'})}catch(e){return show({kind:'Reminder',text:`Import could not be completed: ${e.message}`,context:'Your original export was not changed'})}}
function available(){const now=Date.now(),all=readStore().filter(x=>!x.done&&(!x.snoozedUntil||x.snoozedUntil<=now));return all.length?all:seed}
function next(){const p=available().filter(x=>!current||x.id!==current.id||x.text!==current.text);current=p[Math.floor(Math.random()*p.length)]||available()[0];return current}
function bounds(){const a=screen.getDisplayNearestPoint(screen.getCursorScreenPoint()).workArea;return{x:a.x+a.width-W-16,y:a.y+a.height-H-16,width:W,height:H}}
function createWindow(){win=new BrowserWindow({width:W,height:H,show:false,frame:false,transparent:true,resizable:false,movable:false,maximizable:false,minimizable:false,fullscreenable:false,alwaysOnTop:true,skipTaskbar:true,focusable:false,hasShadow:false,webPreferences:{contextIsolation:true,nodeIntegration:false,preload:path.join(__dirname,'preload.js')}});win.setMinimumSize(W,H);win.setMaximumSize(W,H);win.loadFile(path.join(__dirname,'app','index.html'));win.on('close',e=>{if(!isQuitting){e.preventDefault();win.hide()}})}
function startHide(){clearTimeout(hideTimer);hideTimer=setTimeout(()=>{if(hovered)return startHide();if(win)win.hide()},AUTO_HIDE)}
function show(item){if(item)current=item;else if(!current)next();if(!win)return current;win.setBounds(bounds());win.webContents.send('display-spark',current);win.showInactive();startHide();return current}
function capture(){const t=clean(clipboard.readText());if(!t)return show({kind:'Reminder',text:'Copy a useful part of a ChatGPT or Gemini conversation, then press Ctrl+Shift+S.',context:'Quick capture'});const x=add(t,'Saved from clipboard · AI conversation');return show(x||{kind:'Suggestion',text:'That Spark is already in your local library.',context:'Nothing duplicated'})}
function schedule(){clearTimeout(randomTimer);randomTimer=setTimeout(()=>{current=null;show(next());schedule()},(2+Math.random()*2)*3600000)}
function trayIcon(){const svg='<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" rx="7" fill="#111"/><path d="M18 3L8 18h7l-1 11 10-16h-7z" fill="#ffd928"/></svg>';return nativeImage.createFromDataURL('data:image/svg+xml;base64,'+Buffer.from(svg).toString('base64')).resize({width:16,height:16})}
function createTray(){tray=new Tray(trayIcon());tray.setToolTip('Daily Spark 2');tray.setContextMenu(Menu.buildFromTemplate([{label:'⚡ Show a Spark',click:()=>{current=null;show(next())}},{label:'＋ Save clipboard as Spark',click:capture},{label:'Import ChatGPT History…',click:importHistory},{type:'separator'},{label:'Starts with Windows',type:'checkbox',checked:app.getLoginItemSettings().openAtLogin,click:i=>app.setLoginItemSettings({openAtLogin:i.checked,path:app.getPath('exe')})},{label:'Quit Daily Spark 2',click:()=>{isQuitting=true;app.quit()}}]));tray.on('click',()=>{current=null;show(next())})}
const lock=app.requestSingleInstanceLock();if(!lock)app.quit();else app.whenReady().then(()=>{createWindow();createTray();globalShortcut.register('CommandOrControl+Shift+S',capture);if(app.isPackaged)app.setLoginItemSettings({openAtLogin:true,path:app.getPath('exe')});setTimeout(()=>show(next()),1200);schedule()});
ipcMain.handle('next-spark',()=>{current=null;return show(next())});ipcMain.handle('capture-clipboard',capture);ipcMain.handle('import-history',importHistory);ipcMain.handle('stats',()=>({count:readStore().length}));ipcMain.handle('later-spark',()=>{if(current&&current.id){const a=readStore(),x=a.find(v=>v.id===current.id);if(x)x.snoozedUntil=Date.now()+2*3600000;writeStore(a)}current=null;return show(next())});ipcMain.handle('done-spark',()=>{if(current&&current.id){const a=readStore(),x=a.find(v=>v.id===current.id);if(x)x.done=true;writeStore(a)}current=null;return show(next())});ipcMain.on('close-popup',()=>win&&win.hide());ipcMain.on('popup-hover',(_e,on)=>{hovered=!!on;if(!hovered)startHide()});app.on('before-quit',()=>{isQuitting=true;globalShortcut.unregisterAll()});